// This file statically imports all breed images to ensure they are bundled by Expo/Metro

export const BREED_IMAGES: Record<string, any> = {
    'Amritmahal': require('../assets/breeds/Amritmahal.jpg'),
    'Ayrshire': require('../assets/breeds/Ayrshire.jpg'),
    'Bachaur': require('../assets/breeds/Bachaur.jpg'),
    'Badri': require('../assets/breeds/Badri.jpg'),
    'Bargur': require('../assets/breeds/Bargur.jpg'),
    'Belahi': require('../assets/breeds/Belahi.jpg'),
    'Dagri': require('../assets/breeds/Dagri.jpg'),
    'Dangi': require('../assets/breeds/Dangi.png'),
    'Deoni': require('../assets/breeds/Deoni.jpg'),
    'Gangatiri': require('../assets/breeds/Gangatiri.jpg'),
    'Gaolao': require('../assets/breeds/Gaolao.jpg'),
    'Ghumsari': require('../assets/breeds/Ghumsari.jpg'),
    'Gir': require('../assets/breeds/Gir.jpg'),
    'Hallikar': require('../assets/breeds/Hallikar.jpg'),
    'Hariana': require('../assets/breeds/Hariana.jpg'),
    'Himachali Pahari': require('../assets/breeds/Himachali Pahari.jpg'),
    'Kangayam': require('../assets/breeds/Kangayam.jpg'),
    'Kankrej': require('../assets/breeds/Kankrej.jpg'),
    'Kenkatha': require('../assets/breeds/Kenkatha.jpg'),
    'Khariar': require('../assets/breeds/Khariar.jpg'),
    'Kherigarh': require('../assets/breeds/Kherigarh.jpg'),
    'Khillari': require('../assets/breeds/Khillari.jpg'),
    'Konkan Kapila': require('../assets/breeds/Konkan Kapila.jpg'),
    'Kosali': require('../assets/breeds/Kosali.jpg'),
    'Krishna Valley': require('../assets/breeds/Krishna Valley.jpg'),
    'Ladakhi': require('../assets/breeds/Ladakhi.jpg'),
    'Lakhimi': require('../assets/breeds/Lakhimi.jpg'),
    'Malnad Gidda': require('../assets/breeds/Malnad Gidda.jpg'),
    'Malvi': require('../assets/breeds/Malvi.jpg'),
    'Mewati': require('../assets/breeds/Mewati.jpg'),
    'Motu': require('../assets/breeds/Motu.jpg'),
    'Nagori': require('../assets/breeds/Nagori.jpg'),
    'Nari': require('../assets/breeds/Nari.jpg'),
    'Nimari': require('../assets/breeds/Nimari.jpg'),
    'Ongole': require('../assets/breeds/Ongole.jpg'),
    'Poda Thirupu': require('../assets/breeds/Poda Thirupu.jpg'),
    'Ponwar': require('../assets/breeds/Ponwar.jpg'),
    'Pulikulam': require('../assets/breeds/Pulikulam.jpg'),
    'Punganur': require('../assets/breeds/Punganur.webp'),
    'Purnea': require('../assets/breeds/Purnea.jpg'),
    'Rathi': require('../assets/breeds/Rathi.jpg'),
    'Red Kandhari': require('../assets/breeds/Red Kandhari.jpg'),
    'Red Sindhi': require('../assets/breeds/Red Sindhi.webp'),
    'Sahiwal': require('../assets/breeds/Sahiwal.jpg'),
    'Shweta Kapila': require('../assets/breeds/Shweta Kapila.jpg'),
    'Siri': require('../assets/breeds/Siri.jpg'),
    'Tharparkar': require('../assets/breeds/Tharparkar.jpg'),
    'Thutho': require('../assets/breeds/Thutho.jpg'),
    'Umblachery': require('../assets/breeds/Umblachery.jpg'),
    'Vechur': require('../assets/breeds/Vechur.jpg'),
};

export const getBreedImage = (name: string): any => {
    // Normalization logic: match case insensitive
    const key = Object.keys(BREED_IMAGES).find(k => k.toLowerCase() === name.toLowerCase());
    return key ? BREED_IMAGES[key] : { uri: 'https://via.placeholder.com/400' };
};
